version: '3'

services:
  app:
    container_name: apiService
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    environment:
      REDIS_HOST: redis.db
      REDIS_PORT: 6379
      POSTGRES_HOST: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    depends_on:
      - database
      - redis.db
  database:
    container_name: database
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    restart: unless-stopped
  redis.db:
    container_name: redis.db
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: unless-stopped
volumes:
  postgres_data: